"""create all tables

Revision ID: 5a144640a562
Revises: 
Create Date: 2026-05-20 13:07:21.089888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '5a144640a562'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('performed_by', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('account_value', sa.Float(), nullable=True),
    sa.Column('churn_risk_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_doc', sa.String(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('web_intelligence_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('target_entity', sa.String(), nullable=False),
    sa.Column('scraped_data', sa.JSON(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('sender_email', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sender_email'], ['contacts.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_table('emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('requires_human', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('raw_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index('ix_emails_sender_timestamp', 'emails', ['sender', 'timestamp'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('agent_reasoning_log', sa.JSON(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('proposed_content', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # GIN index with jsonb_ops — must be raw SQL, SQLAlchemy can't autogenerate this
    op.execute(
        "CREATE INDEX ix_emails_raw_entities ON emails USING gin (raw_entities jsonb_ops)"
    )

    # IVFFlat index for pgvector similarity search
    op.execute(
        "CREATE INDEX knowledge_chunks_embedding_idx "
        "ON knowledge_chunks "
        "USING ivfflat (embedding vector_cosine_ops) "
        "WITH (lists = 100)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actions')
    op.drop_index('ix_emails_sender_timestamp', table_name='emails')
    op.drop_table('emails')
    op.drop_table('threads')
    op.drop_table('web_intelligence_cache')
    op.drop_table('knowledge_chunks')
    op.drop_table('contacts')
    op.drop_table('audit_log')
    op.execute("DROP INDEX IF EXISTS ix_emails_raw_entities")
    op.execute("DROP INDEX IF EXISTS knowledge_chunks_embedding_idx")
    # ### end Alembic commands ###
